# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FinalUi11.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import icon
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setMinimumSize(QtCore.QSize(960, 540))
        MainWindow.setMaximumSize(QtCore.QSize(960, 540))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.NavLine = QtWidgets.QFrame(self.centralwidget)
        self.NavLine.setGeometry(QtCore.QRect(0, 40, 960, 2))
        self.NavLine.setAutoFillBackground(False)
        self.NavLine.setStyleSheet("color:white;")
        self.NavLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.NavLine.setLineWidth(0)
        self.NavLine.setMidLineWidth(0)
        self.NavLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.NavLine.setObjectName("NavLine")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(10, 7, 95, 25))
        self.TimeLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 20px;\n"
"line-height: 25px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.TimeLabel.setObjectName("TimeLabel")
        self.CloudLabel = QtWidgets.QLabel(self.centralwidget)
        self.CloudLabel.setGeometry(QtCore.QRect(115, 10, 20, 20))
        self.CloudLabel.setText("")
        self.CloudLabel.setPixmap(QtGui.QPixmap(":/newPrefix/logos/cloud1.png"))
        self.CloudLabel.setObjectName("CloudLabel")
        self.BluetoothOffLabel = QtWidgets.QLabel(self.centralwidget)
        self.BluetoothOffLabel.setGeometry(QtCore.QRect(820, 10, 20, 20))
        self.BluetoothOffLabel.setText("")
        self.BluetoothOffLabel.setPixmap(QtGui.QPixmap(":/newPrefix/logos/bluetooth.png"))
        self.BluetoothOffLabel.setObjectName("BluetoothOffLabel")
        self.NetworkOnIcon = QtWidgets.QLabel(self.centralwidget)
        self.NetworkOnIcon.setGeometry(QtCore.QRect(860, 10, 20, 20))
        self.NetworkOnIcon.setText("")
        self.NetworkOnIcon.setPixmap(QtGui.QPixmap(":/newPrefix/logos/network_icon.png"))
        self.NetworkOnIcon.setObjectName("NetworkOnIcon")
        self.TempLabelApi = QtWidgets.QLabel(self.centralwidget)
        self.TempLabelApi.setGeometry(QtCore.QRect(900, 7, 50, 25))
        self.TempLabelApi.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 20px;\n"
"line-height: 25px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.TempLabelApi.setObjectName("TempLabelApi")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabs.setGeometry(QtCore.QRect(0, 40, 960, 500))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MainTabs.setFont(font)
        self.MainTabs.setMouseTracking(False)
        self.MainTabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MainTabs.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MainTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MainTabs.setAutoFillBackground(False)
        self.MainTabs.setTabPosition(QtWidgets.QTabWidget.East)
        self.MainTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTabs.setIconSize(QtCore.QSize(66, 100))
        self.MainTabs.setElideMode(QtCore.Qt.ElideNone)
        self.MainTabs.setMovable(False)
        self.MainTabs.setTabBarAutoHide(False)
        self.MainTabs.setObjectName("MainTabs")
        self.MusicTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.MusicTab.setFont(font)
        self.MusicTab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MusicTab.setStyleSheet("")
        self.MusicTab.setObjectName("MusicTab")
        self.PlayersTabs = QtWidgets.QTabWidget(self.MusicTab)
        self.PlayersTabs.setGeometry(QtCore.QRect(0, 0, 855, 500))
        self.PlayersTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PlayersTabs.setStyleSheet("")
        self.PlayersTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.PlayersTabs.setIconSize(QtCore.QSize(66, 100))
        self.PlayersTabs.setObjectName("PlayersTabs")
        self.FMTab = QtWidgets.QWidget()
        self.FMTab.setStyleSheet("")
        self.FMTab.setObjectName("FMTab")
        self.NextButtonFm = QtWidgets.QPushButton(self.FMTab)
        self.NextButtonFm.setGeometry(QtCore.QRect(630, 60, 80, 80))
        self.NextButtonFm.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logos/NextBtnFm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextButtonFm.setIcon(icon)
        self.NextButtonFm.setIconSize(QtCore.QSize(30, 53))
        self.NextButtonFm.setObjectName("NextButtonFm")
        self.PreviousBtnFM = QtWidgets.QPushButton(self.FMTab)
        self.PreviousBtnFM.setGeometry(QtCore.QRect(50, 60, 80, 80))
        self.PreviousBtnFM.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/logos/PreviousBtnFm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousBtnFM.setIcon(icon1)
        self.PreviousBtnFM.setIconSize(QtCore.QSize(30, 53))
        self.PreviousBtnFM.setObjectName("PreviousBtnFM")
        self.FreqLabelFM = QtWidgets.QLabel(self.FMTab)
        self.FreqLabelFM.setGeometry(QtCore.QRect(236, 50, 287, 81))
        self.FreqLabelFM.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 64px;\n"
"line-height: 81px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.FreqLabelFM.setObjectName("FreqLabelFM")
        self.Channel1BtnFM = QtWidgets.QPushButton(self.FMTab)
        self.Channel1BtnFM.setGeometry(QtCore.QRect(50, 230, 120, 120))
        self.Channel1BtnFM.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #FFFFFF;")
        self.Channel1BtnFM.setObjectName("Channel1BtnFM")
        self.Channel2BtnFM = QtWidgets.QPushButton(self.FMTab)
        self.Channel2BtnFM.setGeometry(QtCore.QRect(185, 230, 120, 120))
        self.Channel2BtnFM.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #FFFFFF;")
        self.Channel2BtnFM.setObjectName("Channel2BtnFM")
        self.Channel3BtnFM = QtWidgets.QPushButton(self.FMTab)
        self.Channel3BtnFM.setGeometry(QtCore.QRect(320, 230, 120, 120))
        self.Channel3BtnFM.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #FFFFFF;")
        self.Channel3BtnFM.setObjectName("Channel3BtnFM")
        self.Channel4BtnFM = QtWidgets.QPushButton(self.FMTab)
        self.Channel4BtnFM.setGeometry(QtCore.QRect(455, 230, 120, 120))
        self.Channel4BtnFM.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #FFFFFF;")
        self.Channel4BtnFM.setObjectName("Channel4BtnFM")
        self.Channel5BtnFM = QtWidgets.QPushButton(self.FMTab)
        self.Channel5BtnFM.setGeometry(QtCore.QRect(590, 230, 120, 120))
        self.Channel5BtnFM.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #FFFFFF;")
        self.Channel5BtnFM.setObjectName("Channel5BtnFM")
        self.FMLine = QtWidgets.QFrame(self.FMTab)
        self.FMLine.setGeometry(QtCore.QRect(0, 420, 770, 2))
        self.FMLine.setStyleSheet("color:white;")
        self.FMLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FMLine.setLineWidth(2)
        self.FMLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.FMLine.setObjectName("FMLine")
        self.BandBleButton = QtWidgets.QPushButton(self.FMTab)
        self.BandBleButton.setGeometry(QtCore.QRect(0, 428, 100, 58))
        self.BandBleButton.setStyleSheet("\n"
"border:2px solid black;\n"
"border-right-color: rgb(255, 255, 255);")
        self.BandBleButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/logos/BandFM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BandBleButton.setIcon(icon2)
        self.BandBleButton.setIconSize(QtCore.QSize(40, 40))
        self.BandBleButton.setObjectName("BandBleButton")
        self.StationBtnFM = QtWidgets.QPushButton(self.FMTab)
        self.StationBtnFM.setGeometry(QtCore.QRect(101, 428, 100, 58))
        self.StationBtnFM.setStyleSheet("border:2px solid black;\n"
"border-right-color: rgb(255, 255, 255);")
        self.StationBtnFM.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/logos/StationIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StationBtnFM.setIcon(icon3)
        self.StationBtnFM.setIconSize(QtCore.QSize(40, 40))
        self.StationBtnFM.setObjectName("StationBtnFM")
        self.TuneBtnFM = QtWidgets.QPushButton(self.FMTab)
        self.TuneBtnFM.setGeometry(QtCore.QRect(200, 428, 100, 58))
        self.TuneBtnFM.setStyleSheet("border:2px solid black;\n"
"border-right-color: rgb(255, 255, 255);")
        self.TuneBtnFM.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/logos/TuneIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TuneBtnFM.setIcon(icon4)
        self.TuneBtnFM.setIconSize(QtCore.QSize(40, 40))
        self.TuneBtnFM.setObjectName("TuneBtnFM")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/logos/FMTABICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayersTabs.addTab(self.FMTab, icon5, "")
        self.BLETAB = QtWidgets.QWidget()
        self.BLETAB.setObjectName("BLETAB")
        self.TrackIconBLE = QtWidgets.QLabel(self.BLETAB)
        self.TrackIconBLE.setGeometry(QtCore.QRect(80, 70, 180, 180))
        self.TrackIconBLE.setText("")
        self.TrackIconBLE.setPixmap(QtGui.QPixmap(":/newPrefix/logos/TrackIConBLE.png"))
        self.TrackIconBLE.setObjectName("TrackIconBLE")
        self.TitleLabelBLE = QtWidgets.QLabel(self.BLETAB)
        self.TitleLabelBLE.setGeometry(QtCore.QRect(300, 100, 300, 35))
        self.TitleLabelBLE.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"line-height: 35px;\n"
"\n"
"color: #FFFFFF;")
        self.TitleLabelBLE.setObjectName("TitleLabelBLE")
        self.AlbumLabelBLE = QtWidgets.QLabel(self.BLETAB)
        self.AlbumLabelBLE.setGeometry(QtCore.QRect(300, 142, 300, 35))
        self.AlbumLabelBLE.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"line-height: 35px;\n"
"\n"
"color: #FFFFFF;")
        self.AlbumLabelBLE.setObjectName("AlbumLabelBLE")
        self.ArtistLabelBLE = QtWidgets.QLabel(self.BLETAB)
        self.ArtistLabelBLE.setGeometry(QtCore.QRect(300, 195, 300, 35))
        self.ArtistLabelBLE.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"line-height: 35px;\n"
"\n"
"color: #FFFFFF;")
        self.ArtistLabelBLE.setObjectName("ArtistLabelBLE")
        self.BLELine = QtWidgets.QFrame(self.BLETAB)
        self.BLELine.setGeometry(QtCore.QRect(0, 420, 770, 3))
        self.BLELine.setStyleSheet("color:white;")
        self.BLELine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BLELine.setLineWidth(0)
        self.BLELine.setFrameShape(QtWidgets.QFrame.HLine)
        self.BLELine.setObjectName("BLELine")
        self.BLEButtonBLE = QtWidgets.QPushButton(self.BLETAB)
        self.BLEButtonBLE.setGeometry(QtCore.QRect(130, 420, 100, 80))
        self.BLEButtonBLE.setStyleSheet("border:2px solid  white;")
        self.BLEButtonBLE.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/logos/BLeSourceBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BLEButtonBLE.setIcon(icon6)
        self.BLEButtonBLE.setIconSize(QtCore.QSize(47, 38))
        self.BLEButtonBLE.setObjectName("BLEButtonBLE")
        self.PauseBtnBLE = QtWidgets.QPushButton(self.BLETAB)
        self.PauseBtnBLE.setGeometry(QtCore.QRect(330, 421, 100, 80))
        self.PauseBtnBLE.setStyleSheet("border:2px solid white;")
        self.PauseBtnBLE.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/logos/PauseBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PauseBtnBLE.setIcon(icon7)
        self.PauseBtnBLE.setIconSize(QtCore.QSize(40, 40))
        self.PauseBtnBLE.setObjectName("PauseBtnBLE")
        self.PreviousBtnBLE = QtWidgets.QPushButton(self.BLETAB)
        self.PreviousBtnBLE.setGeometry(QtCore.QRect(230, 420, 100, 80))
        self.PreviousBtnBLE.setStyleSheet("border:2px solid white;")
        self.PreviousBtnBLE.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/logos/PreviousBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousBtnBLE.setIcon(icon8)
        self.PreviousBtnBLE.setIconSize(QtCore.QSize(40, 40))
        self.PreviousBtnBLE.setObjectName("PreviousBtnBLE")
        self.NextBtnBLE = QtWidgets.QPushButton(self.BLETAB)
        self.NextBtnBLE.setGeometry(QtCore.QRect(430, 420, 100, 80))
        self.NextBtnBLE.setStyleSheet("border:2px solid  white;")
        self.NextBtnBLE.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/logos/NextBtnBLE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextBtnBLE.setIcon(icon9)
        self.NextBtnBLE.setIconSize(QtCore.QSize(40, 40))
        self.NextBtnBLE.setObjectName("NextBtnBLE")
        self.SelectBtnBLE = QtWidgets.QPushButton(self.BLETAB)
        self.SelectBtnBLE.setGeometry(QtCore.QRect(530, 420, 100, 80))
        self.SelectBtnBLE.setStyleSheet("border:2px solid white;")
        self.SelectBtnBLE.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/logos/SelectBtnBLE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectBtnBLE.setIcon(icon10)
        self.SelectBtnBLE.setIconSize(QtCore.QSize(40, 40))
        self.SelectBtnBLE.setObjectName("SelectBtnBLE")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/logos/BLETABICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayersTabs.addTab(self.BLETAB, icon11, "")
        self.USBTab = QtWidgets.QWidget()
        self.USBTab.setObjectName("USBTab")
        self.USBLine = QtWidgets.QFrame(self.USBTab)
        self.USBLine.setGeometry(QtCore.QRect(0, 421, 770, 3))
        self.USBLine.setStyleSheet("color:white;")
        self.USBLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.USBLine.setLineWidth(0)
        self.USBLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.USBLine.setObjectName("USBLine")
        self.PreviousBtnUSB = QtWidgets.QPushButton(self.USBTab)
        self.PreviousBtnUSB.setGeometry(QtCore.QRect(230, 420, 100, 80))
        self.PreviousBtnUSB.setStyleSheet("border:2px solid white;")
        self.PreviousBtnUSB.setText("")
        self.PreviousBtnUSB.setIcon(icon8)
        self.PreviousBtnUSB.setIconSize(QtCore.QSize(40, 40))
        self.PreviousBtnUSB.setObjectName("PreviousBtnUSB")
        self.PauseBtnUSB = QtWidgets.QPushButton(self.USBTab)
        self.PauseBtnUSB.setGeometry(QtCore.QRect(330, 420, 100, 80))
        self.PauseBtnUSB.setStyleSheet("border:2px solid white;")
        self.PauseBtnUSB.setText("")
        self.PauseBtnUSB.setIcon(icon7)
        self.PauseBtnUSB.setIconSize(QtCore.QSize(40, 40))
        self.PauseBtnUSB.setObjectName("PauseBtnUSB")
        self.NextBtnUSB = QtWidgets.QPushButton(self.USBTab)
        self.NextBtnUSB.setGeometry(QtCore.QRect(430, 420, 100, 80))
        self.NextBtnUSB.setStyleSheet("border:2px solid  white;")
        self.NextBtnUSB.setText("")
        self.NextBtnUSB.setIcon(icon9)
        self.NextBtnUSB.setIconSize(QtCore.QSize(40, 40))
        self.NextBtnUSB.setObjectName("NextBtnUSB")
        self.TrackIconUSB = QtWidgets.QLabel(self.USBTab)
        self.TrackIconUSB.setGeometry(QtCore.QRect(448, 40, 180, 180))
        self.TrackIconUSB.setText("")
        self.TrackIconUSB.setPixmap(QtGui.QPixmap(":/newPrefix/logos/TrackIConBLE.png"))
        self.TrackIconUSB.setObjectName("TrackIconUSB")
        self.SongNameLabeUSB = QtWidgets.QLabel(self.USBTab)
        self.SongNameLabeUSB.setGeometry(QtCore.QRect(384, 250, 300, 30))
        self.SongNameLabeUSB.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"line-height: 35px;\n"
"\n"
"color: #FFFFFF;")
        self.SongNameLabeUSB.setAlignment(QtCore.Qt.AlignCenter)
        self.SongNameLabeUSB.setObjectName("SongNameLabeUSB")
        self.ProgressBarUSB = QtWidgets.QProgressBar(self.USBTab)
        self.ProgressBarUSB.setGeometry(QtCore.QRect(378, 350, 304, 10))
        self.ProgressBarUSB.setStyleSheet("QProgressBar:horizontal {\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"background: Black;\n"
"padding: 1px;\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"background: #90D8FF;\n"
"}")
        self.ProgressBarUSB.setMinimum(0)
        self.ProgressBarUSB.setProperty("value", 33)
        self.ProgressBarUSB.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressBarUSB.setTextVisible(False)
        self.ProgressBarUSB.setInvertedAppearance(False)
        self.ProgressBarUSB.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBarUSB.setObjectName("ProgressBarUSB")
        self.SongLoadButtonUSB = QtWidgets.QPushButton(self.USBTab)
        self.SongLoadButtonUSB.setGeometry(QtCore.QRect(0, 0, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SongLoadButtonUSB.sizePolicy().hasHeightForWidth())
        self.SongLoadButtonUSB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.SongLoadButtonUSB.setFont(font)
        self.SongLoadButtonUSB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SongLoadButtonUSB.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 23px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"border: 2px solid rgb(255, 255, 255);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/logos/ReloadButtonIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SongLoadButtonUSB.setIcon(icon12)
        self.SongLoadButtonUSB.setIconSize(QtCore.QSize(20, 20))
        self.SongLoadButtonUSB.setAutoDefault(False)
        self.SongLoadButtonUSB.setDefault(False)
        self.SongLoadButtonUSB.setFlat(False)
        self.SongLoadButtonUSB.setObjectName("SongLoadButtonUSB")
        self.SongListWidgetUSB = QtWidgets.QListWidget(self.USBTab)
        self.SongListWidgetUSB.setGeometry(QtCore.QRect(0, 50, 300, 371))
        self.SongListWidgetUSB.setObjectName("SongListWidgetUSB")
        self.SongStartTimeLabelUSB = QtWidgets.QLabel(self.USBTab)
        self.SongStartTimeLabelUSB.setGeometry(QtCore.QRect(322, 346, 44, 18))
        self.SongStartTimeLabelUSB.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.SongStartTimeLabelUSB.setObjectName("SongStartTimeLabelUSB")
        self.SongEndTimeLabelUSB = QtWidgets.QLabel(self.USBTab)
        self.SongEndTimeLabelUSB.setGeometry(QtCore.QRect(692, 346, 43, 18))
        self.SongEndTimeLabelUSB.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.SongEndTimeLabelUSB.setObjectName("SongEndTimeLabelUSB")
        self.ProgressBarUSB.raise_()
        self.USBLine.raise_()
        self.PreviousBtnUSB.raise_()
        self.PauseBtnUSB.raise_()
        self.NextBtnUSB.raise_()
        self.TrackIconUSB.raise_()
        self.SongNameLabeUSB.raise_()
        self.SongLoadButtonUSB.raise_()
        self.SongListWidgetUSB.raise_()
        self.SongStartTimeLabelUSB.raise_()
        self.SongEndTimeLabelUSB.raise_()
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/logos/USBTABICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayersTabs.addTab(self.USBTab, icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/logos/MusicTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTabs.addTab(self.MusicTab, icon14, "")
        self.CallingTab = QtWidgets.QWidget()
        self.CallingTab.setObjectName("CallingTab")
        self.CallingTabHRLine = QtWidgets.QFrame(self.CallingTab)
        self.CallingTabHRLine.setGeometry(QtCore.QRect(380, 0, 3, 500))
        self.CallingTabHRLine.setStyleSheet("color:white;")
        self.CallingTabHRLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CallingTabHRLine.setLineWidth(0)
        self.CallingTabHRLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.CallingTabHRLine.setObjectName("CallingTabHRLine")
        self.Person1Call = QtWidgets.QPushButton(self.CallingTab)
        self.Person1Call.setGeometry(QtCore.QRect(39, 41, 300, 60))
        self.Person1Call.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 5px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #000000;")
        self.Person1Call.setObjectName("Person1Call")
        self.Person2Call = QtWidgets.QPushButton(self.CallingTab)
        self.Person2Call.setGeometry(QtCore.QRect(39, 126, 300, 60))
        self.Person2Call.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 5px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #000000;")
        self.Person2Call.setObjectName("Person2Call")
        self.Person3Call = QtWidgets.QPushButton(self.CallingTab)
        self.Person3Call.setGeometry(QtCore.QRect(39, 211, 300, 60))
        self.Person3Call.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 5px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #000000;")
        self.Person3Call.setObjectName("Person3Call")
        self.Person4Call = QtWidgets.QPushButton(self.CallingTab)
        self.Person4Call.setGeometry(QtCore.QRect(39, 296, 300, 60))
        self.Person4Call.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 5px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #000000;")
        self.Person4Call.setObjectName("Person4Call")
        self.Person5Call = QtWidgets.QPushButton(self.CallingTab)
        self.Person5Call.setGeometry(QtCore.QRect(39, 381, 300, 60))
        self.Person5Call.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 5px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"\n"
"color: #000000;")
        self.Person5Call.setObjectName("Person5Call")
        self.label = QtWidgets.QLabel(self.CallingTab)
        self.label.setGeometry(QtCore.QRect(499, 110, 240, 240))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/logos/callingIcon.png"))
        self.label.setObjectName("label")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/logos/PhoneTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTabs.addTab(self.CallingTab, icon15, "")
        self.CameraTab = QtWidgets.QWidget()
        self.CameraTab.setObjectName("CameraTab")
        self.CameraTabBlueBackground = QtWidgets.QLabel(self.CameraTab)
        self.CameraTabBlueBackground.setGeometry(QtCore.QRect(0, 0, 100, 500))
        self.CameraTabBlueBackground.setStyleSheet("background-color:#90D8FF;")
        self.CameraTabBlueBackground.setText("")
        self.CameraTabBlueBackground.setObjectName("CameraTabBlueBackground")
        self.FrontCameraButton = QtWidgets.QPushButton(self.CameraTab)
        self.FrontCameraButton.setGeometry(QtCore.QRect(10, 110, 80, 80))
        self.FrontCameraButton.setStyleSheet("border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"background: #90D8FF;\n"
"")
        self.FrontCameraButton.setObjectName("FrontCameraButton")
        self.FrontCameraView = QtWidgets.QLabel(self.CameraTab)
        self.FrontCameraView.setGeometry(QtCore.QRect(110, 10, 351, 221))
        self.FrontCameraView.setStyleSheet("")
        self.FrontCameraView.setText("")
        self.FrontCameraView.setPixmap(QtGui.QPixmap(":/newPrefix/logos/camera2Icon.png"))
        self.FrontCameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.FrontCameraView.setObjectName("FrontCameraView")
        self.BackCameraButton = QtWidgets.QPushButton(self.CameraTab)
        self.BackCameraButton.setGeometry(QtCore.QRect(10, 200, 80, 80))
        self.BackCameraButton.setStyleSheet("border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"background: #90D8FF;\n"
"")
        self.BackCameraButton.setObjectName("BackCameraButton")
        self.Survillence1CameraButton = QtWidgets.QPushButton(self.CameraTab)
        self.Survillence1CameraButton.setGeometry(QtCore.QRect(10, 300, 80, 80))
        self.Survillence1CameraButton.setStyleSheet("border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"background: #90D8FF;\n"
"")
        self.Survillence1CameraButton.setObjectName("Survillence1CameraButton")
        self.Survillence2CameraButton = QtWidgets.QPushButton(self.CameraTab)
        self.Survillence2CameraButton.setGeometry(QtCore.QRect(10, 400, 80, 80))
        self.Survillence2CameraButton.setStyleSheet("border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"background: #90D8FF;\n"
"")
        self.Survillence2CameraButton.setObjectName("Survillence2CameraButton")
        self.GalleryCameraButton = QtWidgets.QPushButton(self.CameraTab)
        self.GalleryCameraButton.setGeometry(QtCore.QRect(10, 10, 80, 80))
        self.GalleryCameraButton.setStyleSheet("border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"background: white;\n"
"")
        self.GalleryCameraButton.setObjectName("GalleryCameraButton")
        self.CallingTabHRLine_2 = QtWidgets.QFrame(self.CameraTab)
        self.CallingTabHRLine_2.setGeometry(QtCore.QRect(480, 0, 3, 500))
        self.CallingTabHRLine_2.setStyleSheet("color:white;")
        self.CallingTabHRLine_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CallingTabHRLine_2.setLineWidth(0)
        self.CallingTabHRLine_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.CallingTabHRLine_2.setObjectName("CallingTabHRLine_2")
        self.USBLine_2 = QtWidgets.QFrame(self.CameraTab)
        self.USBLine_2.setGeometry(QtCore.QRect(100, 250, 750, 3))
        self.USBLine_2.setStyleSheet("color:white;")
        self.USBLine_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.USBLine_2.setLineWidth(0)
        self.USBLine_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.USBLine_2.setObjectName("USBLine_2")
        self.BackCameraView = QtWidgets.QLabel(self.CameraTab)
        self.BackCameraView.setGeometry(QtCore.QRect(490, 10, 351, 221))
        self.BackCameraView.setStyleSheet("")
        self.BackCameraView.setText("")
        self.BackCameraView.setPixmap(QtGui.QPixmap(":/newPrefix/logos/camera2Icon.png"))
        self.BackCameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.BackCameraView.setObjectName("BackCameraView")
        self.Survilence2CameraView = QtWidgets.QLabel(self.CameraTab)
        self.Survilence2CameraView.setGeometry(QtCore.QRect(490, 260, 351, 221))
        self.Survilence2CameraView.setStyleSheet("")
        self.Survilence2CameraView.setText("")
        self.Survilence2CameraView.setPixmap(QtGui.QPixmap(":/newPrefix/logos/camera2Icon.png"))
        self.Survilence2CameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.Survilence2CameraView.setObjectName("Survilence2CameraView")
        self.Survilence1CameraView = QtWidgets.QLabel(self.CameraTab)
        self.Survilence1CameraView.setGeometry(QtCore.QRect(110, 260, 351, 221))
        self.Survilence1CameraView.setStyleSheet("")
        self.Survilence1CameraView.setText("")
        self.Survilence1CameraView.setPixmap(QtGui.QPixmap(":/newPrefix/logos/camera2Icon.png"))
        self.Survilence1CameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.Survilence1CameraView.setObjectName("Survilence1CameraView")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/newPrefix/logos/CameraTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTabs.addTab(self.CameraTab, icon16, "")
        self.StatusTab = QtWidgets.QWidget()
        self.StatusTab.setObjectName("StatusTab")
        self.InternalStatusTabs = QtWidgets.QTabWidget(self.StatusTab)
        self.InternalStatusTabs.setGeometry(QtCore.QRect(0, 0, 855, 500))
        self.InternalStatusTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InternalStatusTabs.setStyleSheet("")
        self.InternalStatusTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.InternalStatusTabs.setIconSize(QtCore.QSize(66, 100))
        self.InternalStatusTabs.setObjectName("InternalStatusTabs")
        self.ColorPickerTab = QtWidgets.QWidget()
        self.ColorPickerTab.setStyleSheet("")
        self.ColorPickerTab.setObjectName("ColorPickerTab")
        self.BritnessVerticalSlider = QtWidgets.QSlider(self.ColorPickerTab)
        self.BritnessVerticalSlider.setGeometry(QtCore.QRect(530, 83, 100, 333))
        self.BritnessVerticalSlider.setStyleSheet("")
        self.BritnessVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.BritnessVerticalSlider.setObjectName("BritnessVerticalSlider")
        self.ColorPickerButton = QtWidgets.QPushButton(self.ColorPickerTab)
        self.ColorPickerButton.setGeometry(QtCore.QRect(100, 83, 300, 300))
        self.ColorPickerButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/newPrefix/logos/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ColorPickerButton.setIcon(icon17)
        self.ColorPickerButton.setIconSize(QtCore.QSize(300, 300))
        self.ColorPickerButton.setObjectName("ColorPickerButton")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/newPrefix/logos/ColorPicker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InternalStatusTabs.addTab(self.ColorPickerTab, icon18, "")
        self.FuelTab = QtWidgets.QWidget()
        self.FuelTab.setObjectName("FuelTab")
        self.WhiteBackgroundFuelTab = QtWidgets.QLabel(self.FuelTab)
        self.WhiteBackgroundFuelTab.setGeometry(QtCore.QRect(145, 125, 470, 250))
        self.WhiteBackgroundFuelTab.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 15px;")
        self.WhiteBackgroundFuelTab.setText("")
        self.WhiteBackgroundFuelTab.setObjectName("WhiteBackgroundFuelTab")
        self.FuelBar1 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar1.setGeometry(QtCore.QRect(155, 135, 60, 230))
        self.FuelBar1.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar1.setText("")
        self.FuelBar1.setObjectName("FuelBar1")
        self.FuelBar2 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar2.setGeometry(QtCore.QRect(220, 135, 60, 230))
        self.FuelBar2.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar2.setText("")
        self.FuelBar2.setObjectName("FuelBar2")
        self.FuelBar3 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar3.setGeometry(QtCore.QRect(285, 135, 60, 230))
        self.FuelBar3.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar3.setText("")
        self.FuelBar3.setObjectName("FuelBar3")
        self.FuelBar4 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar4.setGeometry(QtCore.QRect(350, 135, 60, 230))
        self.FuelBar4.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar4.setText("")
        self.FuelBar4.setObjectName("FuelBar4")
        self.FuelBar5 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar5.setGeometry(QtCore.QRect(415, 135, 60, 230))
        self.FuelBar5.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar5.setText("")
        self.FuelBar5.setObjectName("FuelBar5")
        self.FuelBar6 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar6.setGeometry(QtCore.QRect(480, 135, 60, 230))
        self.FuelBar6.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar6.setText("")
        self.FuelBar6.setObjectName("FuelBar6")
        self.FuelBar7 = QtWidgets.QLabel(self.FuelTab)
        self.FuelBar7.setGeometry(QtCore.QRect(545, 135, 60, 230))
        self.FuelBar7.setStyleSheet("background: #46DB00;\n"
"border-radius: 10px;")
        self.FuelBar7.setText("")
        self.FuelBar7.setObjectName("FuelBar7")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/newPrefix/logos/FuelTab1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InternalStatusTabs.addTab(self.FuelTab, icon19, "")
        self.FireHydrant = QtWidgets.QWidget()
        self.FireHydrant.setObjectName("FireHydrant")
        self.WeightLabel = QtWidgets.QLabel(self.FireHydrant)
        self.WeightLabel.setGeometry(QtCore.QRect(123, 40, 340, 363))
        self.WeightLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.WeightLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 288px;\n"
"line-height: 363px;\n"
"/* identical to box height */\n"
"\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.WeightLabel.setObjectName("WeightLabel")
        self.GramLabel = QtWidgets.QLabel(self.FireHydrant)
        self.GramLabel.setGeometry(QtCore.QRect(463, 239, 220, 121))
        self.GramLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 96px;\n"
"line-height: 121px;\n"
"/* identical to box height */\n"
"\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.GramLabel.setObjectName("GramLabel")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/newPrefix/logos/FireHydarantIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InternalStatusTabs.addTab(self.FireHydrant, icon20, "")
        self.MapsTab = QtWidgets.QWidget()
        self.MapsTab.setObjectName("MapsTab")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/newPrefix/logos/MapsTab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InternalStatusTabs.addTab(self.MapsTab, icon21, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.LoginLabel = QtWidgets.QLabel(self.SettingsTab)
        self.LoginLabel.setGeometry(QtCore.QRect(322, 67, 116, 32))
        self.LoginLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 90%;\n"
"/* or 32px */\n"
"\n"
"text-align: center;\n"
"text-transform: uppercase;\n"
"\n"
"color: #FFFFFF;")
        self.LoginLabel.setObjectName("LoginLabel")
        self.UserNameLabel = QtWidgets.QLabel(self.SettingsTab)
        self.UserNameLabel.setGeometry(QtCore.QRect(186, 142, 117, 16))
        self.UserNameLabel.setStyleSheet("\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 90%;\n"
"/* or 16px */\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.UserNameLabel.setObjectName("UserNameLabel")
        self.UserNameInput = QtWidgets.QLineEdit(self.SettingsTab)
        self.UserNameInput.setGeometry(QtCore.QRect(180, 162, 400, 50))
        self.UserNameInput.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;")
        self.UserNameInput.setObjectName("UserNameInput")
        self.PasswordNameLabel = QtWidgets.QLabel(self.SettingsTab)
        self.PasswordNameLabel.setGeometry(QtCore.QRect(186, 242, 113, 16))
        self.PasswordNameLabel.setStyleSheet("\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 90%;\n"
"/* or 16px */\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.PasswordNameLabel.setObjectName("PasswordNameLabel")
        self.PasswordNameInput = QtWidgets.QLineEdit(self.SettingsTab)
        self.PasswordNameInput.setGeometry(QtCore.QRect(180, 262, 400, 50))
        self.PasswordNameInput.setStyleSheet("border: 2px solid #FFFFFF;\n"
"box-sizing: border-box;\n"
"border-radius: 10px;")
        self.PasswordNameInput.setObjectName("PasswordNameInput")
        self.LoginButtonSettings = QtWidgets.QPushButton(self.SettingsTab)
        self.LoginButtonSettings.setGeometry(QtCore.QRect(180, 342, 400, 50))
        self.LoginButtonSettings.setStyleSheet("\n"
"background: #C4C4C4;\n"
"border-radius: 10px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 90%;")
        self.LoginButtonSettings.setObjectName("LoginButtonSettings")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/newPrefix/logos/SettingsTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InternalStatusTabs.addTab(self.SettingsTab, icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/newPrefix/logos/StatusTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTabs.addTab(self.StatusTab, icon23, "")
        self.ParkingTab = QtWidgets.QWidget()
        self.ParkingTab.setObjectName("ParkingTab")
        self.BusImageParkingLabel = QtWidgets.QLabel(self.ParkingTab)
        self.BusImageParkingLabel.setGeometry(QtCore.QRect(210, 152, 436, 156))
        self.BusImageParkingLabel.setText("")
        self.BusImageParkingLabel.setPixmap(QtGui.QPixmap(":/newPrefix/logos/BusParkingIcon.png"))
        self.BusImageParkingLabel.setObjectName("BusImageParkingLabel")
        self.MuteButtonParkingTab = QtWidgets.QPushButton(self.ParkingTab)
        self.MuteButtonParkingTab.setGeometry(QtCore.QRect(25, 410, 60, 60))
        self.MuteButtonParkingTab.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/newPrefix/logos/MuteButtonParking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MuteButtonParkingTab.setIcon(icon24)
        self.MuteButtonParkingTab.setIconSize(QtCore.QSize(60, 60))
        self.MuteButtonParkingTab.setObjectName("MuteButtonParkingTab")
        self.Line1ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line1ParkingBackUpper.setGeometry(QtCore.QRect(660, 187, 10, 40))
        self.Line1ParkingBackUpper.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line1ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line1ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line1ParkingBackUpper.setObjectName("Line1ParkingBackUpper")
        self.Line2ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line2ParkingBackUpper.setGeometry(QtCore.QRect(680, 179, 10, 48))
        self.Line2ParkingBackUpper.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line2ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line2ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2ParkingBackUpper.setObjectName("Line2ParkingBackUpper")
        self.Line3ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line3ParkingBackUpper.setGeometry(QtCore.QRect(700, 171, 10, 56))
        self.Line3ParkingBackUpper.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line3ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line3ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3ParkingBackUpper.setObjectName("Line3ParkingBackUpper")
        self.Line4ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line4ParkingBackUpper.setGeometry(QtCore.QRect(720, 163, 10, 64))
        self.Line4ParkingBackUpper.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line4ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line4ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4ParkingBackUpper.setObjectName("Line4ParkingBackUpper")
        self.Line5ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line5ParkingBackUpper.setGeometry(QtCore.QRect(740, 155, 10, 72))
        self.Line5ParkingBackUpper.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line5ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line5ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line5ParkingBackUpper.setObjectName("Line5ParkingBackUpper")
        self.Line6ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line6ParkingBackUpper.setGeometry(QtCore.QRect(760, 147, 10, 80))
        self.Line6ParkingBackUpper.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line6ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line6ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line6ParkingBackUpper.setObjectName("Line6ParkingBackUpper")
        self.Line7ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line7ParkingBackUpper.setGeometry(QtCore.QRect(780, 139, 10, 88))
        self.Line7ParkingBackUpper.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line7ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line7ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line7ParkingBackUpper.setObjectName("Line7ParkingBackUpper")
        self.Line8ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line8ParkingBackUpper.setGeometry(QtCore.QRect(800, 131, 10, 96))
        self.Line8ParkingBackUpper.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line8ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line8ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line8ParkingBackUpper.setObjectName("Line8ParkingBackUpper")
        self.Line9ParkingBackUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line9ParkingBackUpper.setGeometry(QtCore.QRect(820, 123, 10, 104))
        self.Line9ParkingBackUpper.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line9ParkingBackUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line9ParkingBackUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line9ParkingBackUpper.setObjectName("Line9ParkingBackUpper")
        self.Line1ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line1ParkingBackDown.setGeometry(QtCore.QRect(660, 233, 10, 40))
        self.Line1ParkingBackDown.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line1ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line1ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line1ParkingBackDown.setObjectName("Line1ParkingBackDown")
        self.Line2ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line2ParkingBackDown.setGeometry(QtCore.QRect(680, 233, 10, 48))
        self.Line2ParkingBackDown.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line2ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line2ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2ParkingBackDown.setObjectName("Line2ParkingBackDown")
        self.Line3ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line3ParkingBackDown.setGeometry(QtCore.QRect(700, 233, 10, 56))
        self.Line3ParkingBackDown.setStyleSheet("background: #FFFF00;\n"
"border-radius: 5px;")
        self.Line3ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line3ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3ParkingBackDown.setObjectName("Line3ParkingBackDown")
        self.Line4ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line4ParkingBackDown.setGeometry(QtCore.QRect(720, 233, 10, 64))
        self.Line4ParkingBackDown.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line4ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line4ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4ParkingBackDown.setObjectName("Line4ParkingBackDown")
        self.Line5ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line5ParkingBackDown.setGeometry(QtCore.QRect(740, 233, 10, 72))
        self.Line5ParkingBackDown.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line5ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line5ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line5ParkingBackDown.setObjectName("Line5ParkingBackDown")
        self.Line6ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line6ParkingBackDown.setGeometry(QtCore.QRect(760, 233, 10, 80))
        self.Line6ParkingBackDown.setStyleSheet("background: #FF7A00;\n"
"border-radius: 5px;")
        self.Line6ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line6ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line6ParkingBackDown.setObjectName("Line6ParkingBackDown")
        self.Line7ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line7ParkingBackDown.setGeometry(QtCore.QRect(780, 233, 10, 88))
        self.Line7ParkingBackDown.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line7ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line7ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line7ParkingBackDown.setObjectName("Line7ParkingBackDown")
        self.Line8ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line8ParkingBackDown.setGeometry(QtCore.QRect(800, 233, 10, 96))
        self.Line8ParkingBackDown.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line8ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line8ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line8ParkingBackDown.setObjectName("Line8ParkingBackDown")
        self.Line9ParkingBackDown = QtWidgets.QFrame(self.ParkingTab)
        self.Line9ParkingBackDown.setGeometry(QtCore.QRect(820, 233, 10, 104))
        self.Line9ParkingBackDown.setStyleSheet("background: #FF0000;\n"
"border-radius: 5px;")
        self.Line9ParkingBackDown.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line9ParkingBackDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line9ParkingBackDown.setObjectName("Line9ParkingBackDown")
        self.Line1ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line1ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 150, 20, 20))
        self.Line1ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:18px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line1ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line1ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line1ParkingBackSideUpper.setObjectName("Line1ParkingBackSideUpper")
        self.Line2ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line2ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 140, 30, 30))
        self.Line2ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:27px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line2ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line2ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2ParkingBackSideUpper.setObjectName("Line2ParkingBackSideUpper")
        self.Line3ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line3ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 130, 40, 40))
        self.Line3ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:36px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line3ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line3ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3ParkingBackSideUpper.setObjectName("Line3ParkingBackSideUpper")
        self.Line4ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line4ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 120, 50, 50))
        self.Line4ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:45px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line4ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line4ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4ParkingBackSideUpper.setObjectName("Line4ParkingBackSideUpper")
        self.Line5ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line5ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 110, 60, 60))
        self.Line5ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:54px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line5ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line5ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line5ParkingBackSideUpper.setObjectName("Line5ParkingBackSideUpper")
        self.Line6ParkingBackSideUpper = QtWidgets.QFrame(self.ParkingTab)
        self.Line6ParkingBackSideUpper.setGeometry(QtCore.QRect(640, 100, 70, 70))
        self.Line6ParkingBackSideUpper.setStyleSheet("background: transparent;\n"
"border-top-right-radius:63px;\n"
"border-top:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line6ParkingBackSideUpper.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line6ParkingBackSideUpper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line6ParkingBackSideUpper.setObjectName("Line6ParkingBackSideUpper")
        self.Line1ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line1ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 20, 20))
        self.Line1ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:18px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line1ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line1ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line1ParkingBackSideLower.setObjectName("Line1ParkingBackSideLower")
        self.Line2ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line2ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 30, 30))
        self.Line2ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:27px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line2ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line2ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2ParkingBackSideLower.setObjectName("Line2ParkingBackSideLower")
        self.Line3ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line3ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 40, 40))
        self.Line3ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:36px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line3ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line3ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3ParkingBackSideLower.setObjectName("Line3ParkingBackSideLower")
        self.Line4ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line4ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 50, 50))
        self.Line4ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:45px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line4ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line4ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4ParkingBackSideLower.setObjectName("Line4ParkingBackSideLower")
        self.Line5ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line5ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 60, 60))
        self.Line5ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:54px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line5ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line5ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line5ParkingBackSideLower.setObjectName("Line5ParkingBackSideLower")
        self.Line6ParkingBackSideLower = QtWidgets.QFrame(self.ParkingTab)
        self.Line6ParkingBackSideLower.setGeometry(QtCore.QRect(640, 290, 70, 70))
        self.Line6ParkingBackSideLower.setStyleSheet("background: transparent;\n"
"border-bottom-right-radius:63px;\n"
"border-bottom:5px solid yellow;\n"
"border-right:5px solid yellow;")
        self.Line6ParkingBackSideLower.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line6ParkingBackSideLower.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line6ParkingBackSideLower.setObjectName("Line6ParkingBackSideLower")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/newPrefix/logos/ParkingTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTabs.addTab(self.ParkingTab, icon25, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainTabs.setCurrentIndex(3)
        self.PlayersTabs.setCurrentIndex(2)
        self.InternalStatusTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimeLabel.setText(_translate("MainWindow", "10:20 AM"))
        self.TempLabelApi.setText(_translate("MainWindow", "25°C"))
        self.FreqLabelFM.setText(_translate("MainWindow", "92.7 MHz"))
        self.Channel1BtnFM.setText(_translate("MainWindow", "1"))
        self.Channel2BtnFM.setText(_translate("MainWindow", "2"))
        self.Channel3BtnFM.setText(_translate("MainWindow", "3"))
        self.Channel4BtnFM.setText(_translate("MainWindow", "4"))
        self.Channel5BtnFM.setText(_translate("MainWindow", "5"))
        self.TitleLabelBLE.setText(_translate("MainWindow", "TITLE"))
        self.AlbumLabelBLE.setText(_translate("MainWindow", "ALBUM"))
        self.ArtistLabelBLE.setText(_translate("MainWindow", "ARTIST"))
        self.SongNameLabeUSB.setText(_translate("MainWindow", "TITLE"))
        self.ProgressBarUSB.setFormat(_translate("MainWindow", "%p%"))
        self.SongLoadButtonUSB.setText(_translate("MainWindow", " ReloadSongs"))
        self.SongStartTimeLabelUSB.setText(_translate("MainWindow", "00:20"))
        self.SongEndTimeLabelUSB.setText(_translate("MainWindow", "04:30"))
        self.Person1Call.setText(_translate("MainWindow", "Manager"))
        self.Person2Call.setText(_translate("MainWindow", "Head Office Pune"))
        self.Person3Call.setText(_translate("MainWindow", "Head Office Indore"))
        self.Person4Call.setText(_translate("MainWindow", "Police"))
        self.Person5Call.setText(_translate("MainWindow", "Ambulance"))
        self.FrontCameraButton.setText(_translate("MainWindow", "Front\n"
"Camera"))
        self.BackCameraButton.setText(_translate("MainWindow", "Back\n"
"Camera"))
        self.Survillence1CameraButton.setText(_translate("MainWindow", "Survillence\n"
"Camera-1"))
        self.Survillence2CameraButton.setText(_translate("MainWindow", "Survillence\n"
"Camera-2"))
        self.GalleryCameraButton.setText(_translate("MainWindow", "Gallery\n"
"View"))
        self.WeightLabel.setText(_translate("MainWindow", "71"))
        self.GramLabel.setText(_translate("MainWindow", "gm"))
        self.LoginLabel.setText(_translate("MainWindow", "LOGIN"))
        self.UserNameLabel.setText(_translate("MainWindow", "Username"))
        self.PasswordNameLabel.setText(_translate("MainWindow", "Password"))
        self.LoginButtonSettings.setText(_translate("MainWindow", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
